Comment out go build part
it doesnt work in multi-language repositories

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -18,9 +18,11 @@ if [ ! -z "$unformatted" ]; then
     exit 1
 fi
 
-go build >&2
-if [[ $? != 0 ]]; then
-    echo >&2 "Go build failed! Please fix the problems before committing."
-    exit 1
-fi
+# go build -o hookbuildoutput >&2
+# if [[ $? != 0 ]]; then
+#     echo >&2 "Go build failed! Please fix the problems before committing."
+#     rm hookbuildoutput
+#     exit 1
+# fi
+# rm hookbuildoutput
 exit 0
